### ISSUE TITLE
more resolution?

### ISSUE THREAD

**Issue by lostiv** [SwaggyMacro/TgStoGifBot#1]
as 128x128 256x256, it's so big

**Comment by SwaggyMacro** [comment]
I will support it when I am free, or maybe you can make a PR. Add two commands or command's args, and specify the width/height parameter.

**Comment by SwaggyMacro** [comment]
Supported.
![image](https://github.com/user-attachments/assets/8e1d92f2-91a4-49fd-8ffc-9c0aebe13f0b)
